# Uncomment the next line to define a global platform for your project
platform :ios, '8.2'

source "https://github.com/CocoaPods/Specs.git"

target 'YNCommonTest' do

  pod "Masonry"
  pod "MJRefresh"
  pod "SDWebImage"
  pod "EBBannerView"

end
